// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC-12OJbFQStCs8brfxYYPeEoGgdZqrCg',
    appId: '1:33068137249:web:26cb698b0e0b69e2f69c60',
    messagingSenderId: '33068137249',
    projectId: 'logincomplete-70113',
    authDomain: 'logincomplete-70113.firebaseapp.com',
    storageBucket: 'logincomplete-70113.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQHVXDyxrYAN5EDRXEj8-zsJs2evyrwPs',
    appId: '1:33068137249:android:61fe84ae588cde68f69c60',
    messagingSenderId: '33068137249',
    projectId: 'logincomplete-70113',
    storageBucket: 'logincomplete-70113.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb1rHCvJTg1o6A942tCD5oUi_DMjHJ8H0',
    appId: '1:33068137249:ios:b9ba43ffc628c69ef69c60',
    messagingSenderId: '33068137249',
    projectId: 'logincomplete-70113',
    storageBucket: 'logincomplete-70113.appspot.com',
    iosClientId: '33068137249-qea11mjfl5lb60t912d6o4j3lvbaovhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplateV1',
  );
}
